# Generated by Django 2.1.2 on 2018-10-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada_programada', models.DateTimeField(null=True)),
                ('data_devolucao_programada', models.DateTimeField(null=True)),
                ('data_retirada', models.DateTimeField(null=True)),
                ('data_devolucao', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEmprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Item para empréstimo',
                'verbose_name_plural': 'Itens para empréstimo',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('matricula', models.CharField(blank=True, max_length=35, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ItemEmprestimo'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='pessoa_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='core.Pessoa'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='pessoa_retirada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_retirada', to='core.Pessoa'),
        ),
    ]
