# Generated by Django 2.1.2 on 2018-10-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181005_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'empréstimo registrado', 'verbose_name_plural': 'empréstimos registrados'},
        ),
        migrations.AlterModelOptions(
            name='itememprestimo',
            options={'verbose_name': 'item para empréstimo', 'verbose_name_plural': 'itens para empréstimo'},
        ),
        migrations.AlterModelOptions(
            name='tipoitem',
            options={'verbose_name': 'tipo de item para empréstimo', 'verbose_name_plural': 'tipos de item para empréstimo'},
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='horas_utilizacao_limite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoitem',
            name='horas_utilizacao_padrao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoitem',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
