# Generated by Django 2.1.2 on 2018-11-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181005_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='itememprestimo',
            name='emprestimo_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Emprestimo'),
        ),
    ]
