# Generated by Django 2.2.4 on 2019-08-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itememprestimo_emprestimo_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itememprestimo',
            name='emprestimo_atual',
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='quantidade_total',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
