# Generated by Django 2.2.4 on 2019-08-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190807_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='itememprestimo',
            name='palavras_chave',
            field=models.TextField(blank=True, help_text='Várias palavras separadas por espaços que auxiliam na busca', null=True),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='horas_utilizacao_limite',
            field=models.IntegerField(blank=True, help_text='Defina o tempo máximo permitido para utilização', null=True),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='quantidade_total',
            field=models.IntegerField(blank=True, default=1, help_text='Defina a quantidade existente para este item. Para bens patrimoniados, utilize o valor 1', null=True),
        ),
    ]
