# Generated by Django 2.2.4 on 2019-08-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190807_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itememprestimo',
            old_name='horas_utilizacao_limite',
            new_name='minutos_utilizacao_limite',
        ),
        migrations.RenameField(
            model_name='tipoitem',
            old_name='horas_utilizacao_padrao',
            new_name='minutos_utilizacao_padrao',
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='necessita_confirmacao_devolucao',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='necessita_confirmacao_retirada',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='quantidade_total',
            field=models.IntegerField(blank=True, default=1, help_text='Defina a quantidade existente para este item. Para bens patrimoniados, utilize o valor 1 e cadastre os demais itens individualmente', null=True),
        ),
    ]
