# Generated by Django 2.2.4 on 2019-08-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190808_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='itememprestimo',
            name='reserva_bloqueada',
            field=models.BooleanField(default=False, help_text='Impede que este item seja reservado', null=True),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='codigo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
