# Generated by Django 2.2.4 on 2019-08-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190808_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de término'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_hora_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de início'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_retirada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora da retirada'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='pessoa_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='core.Pessoa', verbose_name='Pessoa responsável'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='pessoa_retirada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_retirada', to='core.Pessoa', verbose_name='Pessoa a retirar'),
        ),
    ]
