# Generated by Django 2.2.4 on 2019-08-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190808_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='itememprestimo',
            name='reserva_por_fila',
            field=models.BooleanField(default=False, help_text='Permite apenas reserva por fila de espera', null=True),
        ),
    ]
