# Generated by Django 2.2.4 on 2019-08-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190810_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itememprestimo',
            name='bloqueio_minutos_antes',
            field=models.IntegerField(blank=True, default=60, help_text='Impede de reservar minutos antes da próxima reserva (não tem efeito para item com quantidade total maior que 1)', null=True),
        ),
    ]
